# Generated by Django 4.1.7 on 2023-03-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talmudtext',
            name='hebrew_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
