# Generated by Django 4.1.7 on 2023-03-27 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorer', '0002_talmudtext_hebrew_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wikipedia_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.wikipediaarticle')),
            ],
        ),
    ]
